/**
 * Compare accumulator values in contract vs backend
 */

import { createPublicClient, http } from 'viem';
import { sepolia } from 'viem/chains';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const RootChainData = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../backend/abi/RootChain.json'), 'utf-8')
);
const RootChainABI = RootChainData.abi || RootChainData;

const publicClient = createPublicClient({
  chain: sepolia,
  transport: http(process.env.L1_RPC),
});

async function compare() {
  console.log('=== Compare Accumulator Values ===\n');

  // Get from contract
  console.log('--- Contract Accumulator ---');
  const contractAcc = await publicClient.readContract({
    address: process.env.ROOT_CHAIN_ADDRESS as `0x${string}`,
    abi: RootChainABI,
    functionName: 'getAccumulatorValue',
  });
  console.log('Contract accumulator X:', contractAcc.x);
  console.log('Contract accumulator Y:', contractAcc.y);

  // Get from backend
  console.log('\n--- Backend Accumulator ---');
  const resp = await fetch('http://localhost:3001/api/accumulator/value');
  const data = await resp.json();
  console.log('Backend accumulator X:', data.accumulator.x);
  console.log('Backend accumulator Y:', data.accumulator.y);

  // Compare
  console.log('\n--- Comparison ---');
  const contractX = '0x' + contractAcc.x.toString(16);
  const contractY = '0x' + contractAcc.y.toString(16);
  
  const backendX = data.accumulator.x.toLowerCase();
  const backendY = data.accumulator.y.toLowerCase();

  console.log('X Match?', contractX.toLowerCase() === backendX);
  console.log('Y Match?', contractY.toLowerCase() === backendY);

  if (contractX.toLowerCase() !== backendX || contractY.toLowerCase() !== backendY) {
    console.log('\n❌ MISMATCH! Accumulator values are different!');
    console.log('This means:');
    console.log('- Contract accumulator != Backend accumulator');
    console.log('- Witness generated by backend will not work with contract!');
    console.log('- Need to sync accumulator from latest block');
  } else {
    console.log('\n✅ Match! Accumulator values are the same');
  }

  // Check latest block
  console.log('\n--- Latest Block ---');
  const currentBlock = await publicClient.readContract({
    address: process.env.ROOT_CHAIN_ADDRESS as `0x${string}`,
    abi: RootChainABI,
    functionName: 'currentPlasmaBlock',
  });
  console.log('Current block number:', currentBlock);

  if (currentBlock > 0n) {
    const block = await publicClient.readContract({
      address: process.env.ROOT_CHAIN_ADDRESS as `0x${string}`,
      abi: RootChainABI,
      functionName: 'plasmaBlocks',
      args: [currentBlock],
    });
    console.log('Latest block accumulator X:', (block as any).accumulatorValue.x);
    console.log('Latest block accumulator Y:', (block as any).accumulatorValue.y);
  }
}

compare().catch(console.error);
